title: Multicellular Systems and Engineering Lab
description: From spikes to intercellular waves: tuning intercellular Ca2+ signaling dynamics modulates organ size control.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman